version: '3'
services:
  mysql-db:
    image: mysql:5.6
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "3306"

  user-creator:
    build: ct/.
    ports:
      - "3000"
    environment:
      - MYSQL_HOST=mysql-db
    links:
      - mysql-db
    depends_on:
      - mysql-db

  portfolio:
    build: .
    ports:
      - "8088"
    environment:
      - MYSQL_URL=jdbc:mysql://mysql-db:3306/mysql
    links:
      - mysql-db
    depends_on:
      - mysql-db