spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      default_schema: mysql
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: test
name: portfolio-rest
server:
  port: 8081
  servlet:
    contextPath: /portfolio-api